spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kyubit_db
    username: kyubit
    password: kyubitpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # crea/actualiza tablas según las entidades (@Entity)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
