spring:
  # --- Configuración de PostgreSQL comentada temporalmente ---
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/kyubit_db
  #   username: kyubit
  #   password: kyubitpass
  #   driver-class-name: org.postgresql.Driver

  # --- Configuración para H2 (Base de datos en memoria) ---
  # No necesitamos 'datasource' porque Spring Boot la autoconfigura si ve la dependencia H2.
  h2:
    console:
      enabled: true  # Habilita la consola web de H2
      path: /h2-console # La URL para acceder a la consola

  jpa:
    hibernate:
      ddl-auto: create-drop # Para H2, 'create-drop' es ideal. Crea las tablas al iniciar y las borra al apagar.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # ¡IMPORTANTE! Cambiamos el dialecto a H2.
        format_sql: true

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: bWFnbmlmaWNlbnQtc2VjcmV0LWtleS1mb3ItandrLWF1dGhlbnRpY2F0aW9uLXNlc3Npb24=
      expiration: 86400000
      refresh-token:
        expiration: 604800000
